#ifndef RECEIVER_BOARD_PINS_H
#define RECEIVER_BOARD_PINS_H

#include "stc8h_sfr.h"

#define TOY_REMOTE_NRF24_CSN_MASK 0x04u
#define TOY_REMOTE_NRF24_CE_MASK 0x40u
#define TOY_REMOTE_NRF24_IRQ_MASK 0x04u

#define TOY_REMOTE_RX_MOTOR_IN1_MASK 0x08u
#define TOY_REMOTE_RX_MOTOR_IN2_MASK 0x10u
#define TOY_REMOTE_RX_LIGHT_MASK 0x20u
#define TOY_REMOTE_RX_BUZZER_MASK 0x40u
#define TOY_REMOTE_RX_LED_MASK 0x80u
#define TOY_REMOTE_RX_RF_CH_ADD_MASK 0x01u
#define TOY_REMOTE_RX_RF_CH_MINUS_MASK 0x02u
#define TOY_REMOTE_RX_ADC_VOLTAGE_CHANNEL 1u

#define DRV_NRF24L01_CSN_HIGH() do { P1 |= TOY_REMOTE_NRF24_CSN_MASK; } while (0)
#define DRV_NRF24L01_CSN_LOW() do { P1 &= (stc8h_u8)~TOY_REMOTE_NRF24_CSN_MASK; } while (0)
#define DRV_NRF24L01_CE_HIGH() do { P1 |= TOY_REMOTE_NRF24_CE_MASK; } while (0)
#define DRV_NRF24L01_CE_LOW() do { P1 &= (stc8h_u8)~TOY_REMOTE_NRF24_CE_MASK; } while (0)
#define DRV_NRF24L01_IRQ_READ() ((P3 & TOY_REMOTE_NRF24_IRQ_MASK) ? 1u : 0u)

#define TOY_REMOTE_RX_LIGHT_OFF() do { P3 |= TOY_REMOTE_RX_LIGHT_MASK; } while (0)
#define TOY_REMOTE_RX_LIGHT_ON() do { P3 &= (stc8h_u8)~TOY_REMOTE_RX_LIGHT_MASK; } while (0)
#define TOY_REMOTE_RX_BUZZER_OFF() do { P3 |= TOY_REMOTE_RX_BUZZER_MASK; } while (0)
#define TOY_REMOTE_RX_BUZZER_ON() do { P3 &= (stc8h_u8)~TOY_REMOTE_RX_BUZZER_MASK; } while (0)
#define TOY_REMOTE_RX_LED_OFF() do { P3 |= TOY_REMOTE_RX_LED_MASK; } while (0)
#define TOY_REMOTE_RX_LED_ON() do { P3 &= (stc8h_u8)~TOY_REMOTE_RX_LED_MASK; } while (0)
#define TOY_REMOTE_RX_MOTOR_STOP() do { P3 &= (stc8h_u8)~(TOY_REMOTE_RX_MOTOR_IN1_MASK | TOY_REMOTE_RX_MOTOR_IN2_MASK); } while (0)
#define TOY_REMOTE_RX_RF_CH_ADD_ACTIVE() (((P3 & TOY_REMOTE_RX_RF_CH_ADD_MASK) == 0u) ? 1u : 0u)
#define TOY_REMOTE_RX_RF_CH_MINUS_ACTIVE() (((P3 & TOY_REMOTE_RX_RF_CH_MINUS_MASK) == 0u) ? 1u : 0u)

#endif
