#ifndef CONTROLLER_BOARD_PINS_H
#define CONTROLLER_BOARD_PINS_H

#include "stc8h_sfr.h"

#define TOY_REMOTE_NRF24_CSN_MASK 0x04u
#define TOY_REMOTE_NRF24_CE_MASK 0x40u
#define TOY_REMOTE_NRF24_IRQ_MASK 0x04u

#define TOY_REMOTE_TX_EC11_A_MASK 0x02u
#define TOY_REMOTE_TX_EC11_B_MASK 0x01u
#define TOY_REMOTE_TX_EC11_SW_MASK 0x10u
#define TOY_REMOTE_TX_DIR_MASK 0x80u
#define TOY_REMOTE_TX_LIGHT_MASK 0x40u
#define TOY_REMOTE_TX_BUZZER_MASK 0x20u
#define TOY_REMOTE_TX_BRAKE_MASK 0x01u
#define TOY_REMOTE_TX_FN_MASK 0x10u
#define TOY_REMOTE_TX_TM1637_CLK_MASK 0x80u
#define TOY_REMOTE_TX_TM1637_DIO_MASK 0x02u
#define TOY_REMOTE_TX_ADC_STEERING_CHANNEL 11u

STC8H_SBIT(TOY_REMOTE_TX_TM1637_CLK_BIT, 0x90, 7);
STC8H_SBIT(TOY_REMOTE_TX_TM1637_DIO_BIT, 0xB0, 1);
STC8H_SBIT(TOY_REMOTE_NRF24_CSN_BIT, 0x90, 2);
STC8H_SBIT(TOY_REMOTE_NRF24_CE_BIT, 0x90, 6);

#define DRV_NRF24L01_CSN_HIGH() do { TOY_REMOTE_NRF24_CSN_BIT = 1; } while (0)
#define DRV_NRF24L01_CSN_LOW() do { TOY_REMOTE_NRF24_CSN_BIT = 0; } while (0)
#define DRV_NRF24L01_CE_HIGH() do { TOY_REMOTE_NRF24_CE_BIT = 1; } while (0)
#define DRV_NRF24L01_CE_LOW() do { TOY_REMOTE_NRF24_CE_BIT = 0; } while (0)
#define DRV_NRF24L01_IRQ_READ() ((P3 & TOY_REMOTE_NRF24_IRQ_MASK) ? 1u : 0u)

#define TOY_REMOTE_TX_EC11_A_READ() ((P1 & TOY_REMOTE_TX_EC11_A_MASK) ? 1u : 0u)
#define TOY_REMOTE_TX_EC11_B_READ() ((P1 & TOY_REMOTE_TX_EC11_B_MASK) ? 1u : 0u)
#define TOY_REMOTE_TX_EC11_SW_ACTIVE() (((P5 & TOY_REMOTE_TX_EC11_SW_MASK) == 0u) ? 1u : 0u)
#define TOY_REMOTE_TX_DIR_REVERSE() (((P3 & TOY_REMOTE_TX_DIR_MASK) == 0u) ? 1u : 0u)
#define TOY_REMOTE_TX_LIGHT_ACTIVE() (((P3 & TOY_REMOTE_TX_LIGHT_MASK) == 0u) ? 1u : 0u)
#define TOY_REMOTE_TX_BUZZER_ACTIVE() (((P3 & TOY_REMOTE_TX_BUZZER_MASK) == 0u) ? 1u : 0u)
#define TOY_REMOTE_TX_BRAKE_ACTIVE() (((P3 & TOY_REMOTE_TX_BRAKE_MASK) == 0u) ? 1u : 0u)
#define TOY_REMOTE_TX_FN_ACTIVE() (((P3 & TOY_REMOTE_TX_FN_MASK) == 0u) ? 1u : 0u)

#define BOARD_TM1637_CLK_HIGH() do { TOY_REMOTE_TX_TM1637_CLK_BIT = 1; } while (0)
#define BOARD_TM1637_CLK_LOW() do { TOY_REMOTE_TX_TM1637_CLK_BIT = 0; } while (0)
#define BOARD_TM1637_DIO_HIGH() do { TOY_REMOTE_TX_TM1637_DIO_BIT = 1; } while (0)
#define BOARD_TM1637_DIO_LOW() do { TOY_REMOTE_TX_TM1637_DIO_BIT = 0; } while (0)
#define BOARD_TM1637_DIO_READ() ((P3 & TOY_REMOTE_TX_TM1637_DIO_MASK) ? 1u : 0u)

#endif
