[env:STC8H1K08]
platform = intel_mcs51
board = STC8H1K08
build_flags =
    -Isrc
    -I../../Stc8hBase/core
    -I../../Stc8hBase/hal
    -I../../Stc8hBase/drivers
    -I../../Stc8hBase/protocols
    -I../shared
    -DSTC8H_CONFIG_INCLUDE=\"board_config.h\"
    -DSTC8H_PINS_INCLUDE=\"board_pins.h\"
    -DPROTO_RF_LINK_ENABLE_RESET=0
    -DPROTO_RF_LINK_ENABLE_TICK=0
    -DPROTO_RF_LINK_ENABLE_CONNECT=0
    -DPROTO_RF_LINK_ENABLE_SEND_DATA=0
    -DPROTO_RF_LINK_ENABLE_SEND_DATA_FIXED=1
    -DPROTO_RF_LINK_ENABLE_SEND_DATA_FIXED_TRACK_ACK=0
    -DPROTO_RF_LINK_ENABLE_PACKET_ARG_CHECK=0
    -DPROTO_RF_LINK_ENABLE_INIT_TIMEOUT_FIELDS=0
    -DPROTO_RF_LINK_INCLUDE_TIMEOUT_FIELDS=0
    -DPROTO_RF_LINK_TRACK_STATE=0
    -DPROTO_RF_LINK_TRACK_SEQ_RX=0
    -DPROTO_RF_LINK_TRACK_ACK_PENDING=0
    -DPROTO_RF_LINK_ENABLE_SEND_STATUS=0
    -DPROTO_RF_LINK_ENABLE_SEND_HEARTBEAT=0
    -DPROTO_RF_LINK_ENABLE_POLL=0
    -DPROTO_RF_LINK_ENABLE_GET_STATE=0
    -DTOY_REMOTE_ENABLE_CONTROL_SET_SAFE=0
    -DTOY_REMOTE_ENABLE_CONTROL_APPLY_BRAKE=0
    -DTOY_REMOTE_ENABLE_CONTROL_SET_STEERING_FROM_ADC=0
    -DTOY_REMOTE_ENABLE_CONTROL_ADJUST_SPEED=0
    -DTOY_REMOTE_ENABLE_STATUS_SET_VOLTAGE=0
    -DTOY_REMOTE_ENABLE_VALIDATE_CONTROL=0
    -DTOY_REMOTE_ENABLE_VALIDATE_STATUS=0
    -DTOY_REMOTE_ENABLE_PACK_CONTROL=0
    -DTOY_REMOTE_ENABLE_UNPACK_CONTROL=0
    -DTOY_REMOTE_ENABLE_PACK_STATUS=0
    -DTOY_REMOTE_ENABLE_UNPACK_STATUS=0
    -DDRV_EC11_ENABLE_FULL_API=0
    -DDRV_EC11_ENABLE_SMALL_API=1
    -DDRV_EC11_SMALL_STEPS_PER_DETENT=4
    -DDRV_EC11_SMALL_REVERSE=0
    -DDRV_EC11_ENABLE_NULL_CHECK=0
    -DDRV_NRF24L01_ENABLE_READ_FIFO_STATUS=0
    -DDRV_NRF24L01_ENABLE_READ_OBSERVE_TX=0
    -DDRV_NRF24L01_ENABLE_ARG_CHECK=0
    -DDRV_NRF24L01_ENABLE_ADDRESS_API=0
    -DDRV_NRF24L01_ENABLE_PIPE0_FIXED_API=1
    -DDRV_NRF24L01_ENABLE_RAW_API=0
    -DDRV_NRF24L01_ENABLE_ENTER_RX=0
    -DDRV_NRF24L01_ENABLE_ENTER_STANDBY=0
    -DDRV_NRF24L01_ENABLE_DYNAMIC_PAYLOAD=0
    -DDRV_NRF24L01_ENABLE_WRITE_ACK_PAYLOAD=0
    -DDRV_NRF24L01_ENABLE_DISABLE_ACK_PAYLOAD=0
    -DDRV_TM1637_ENABLE_DISPLAY_DIGITS=0
    -DDRV_TM1637_ENABLE_DISPLAY_RAW=0
    -DDRV_TM1637_ENABLE_DISPLAY_RAW4=1
    -DDRV_TM1637_ENABLE_RAW_LEN_CHECK=0
    -DDRV_TM1637_ENABLE_SET_DISPLAY=0
    -DDRV_TM1637_ENABLE_DISPLAY_NUMBER=0
    -DDRV_TM1637_ENABLE_ENCODE_DIGIT=0
    -DDRV_TM1637_ENABLE_CLEAR=0
    -DDRV_TM1637_ENABLE_BRIGHTNESS_STATE=0
    -DDRV_TM1637_FIXED_BRIGHTNESS=1
    -DSTC8H_EEPROM_ENABLE_READ=0
    -DSTC8H_EEPROM_ENABLE_WRITE=0
    -DSTC8H_EEPROM_ENABLE_ERASE=0
    -DSTC8H_EEPROM_ENABLE_FIXED_BLOCK=1
    -DSTC8H_EEPROM_FIXED_ADDR=0
    -DSTC8H_EEPROM_FIXED_SIZE=11
    -DSTC8H_SPI_ENABLE_WRITE=0
